package com.tech_freaks.shopcart.model;

// Generated Jun 19, 2015 4:48:46 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * Cartitem generated by hbm2java
 */
public class Cartitem implements java.io.Serializable {

	private Integer cartitemId;
	private Cart cart;
	private Product product;
	private int quantity;
	private BigDecimal unitprice;
	private BigDecimal totalprice;

	public Cartitem() {
	}

	public Cartitem(Cart cart, Product product, int quantity,
			BigDecimal unitprice, BigDecimal totalprice) {
		this.cart = cart;
		this.product = product;
		this.quantity = quantity;
		this.unitprice = unitprice;
		this.totalprice = totalprice;
	}

	public Integer getCartitemId() {
		return this.cartitemId;
	}

	public void setCartitemId(Integer cartitemId) {
		this.cartitemId = cartitemId;
	}

	public Cart getCart() {
		return this.cart;
	}

	public void setCart(Cart cart) {
		this.cart = cart;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public BigDecimal getUnitprice() {
		return this.unitprice;
	}

	public void setUnitprice(BigDecimal unitprice) {
		this.unitprice = unitprice;
	}

	public BigDecimal getTotalprice() {
		return this.totalprice;
	}

	public void setTotalprice(BigDecimal totalprice) {
		this.totalprice = totalprice;
	}

}
