package com.tech_freaks.shopcart.model;

// Generated Jun 19, 2015 4:48:46 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Cart generated by hbm2java
 */
public class Cart implements java.io.Serializable {

	private Integer cartId;
	private BigDecimal productPrice;
	private BigDecimal shippingPrice;
	private BigDecimal taxPrice;
	private BigDecimal totalPrice;
	private char status;
	private Set cartitems = new HashSet(0);

	public Cart() {
	}

	public Cart(char status) {
		this.status = status;
	}

	public Cart(BigDecimal productPrice, BigDecimal shippingPrice,
			BigDecimal taxPrice, BigDecimal totalPrice, char status,
			Set cartitems) {
		this.productPrice = productPrice;
		this.shippingPrice = shippingPrice;
		this.taxPrice = taxPrice;
		this.totalPrice = totalPrice;
		this.status = status;
		this.cartitems = cartitems;
	}

	public Integer getCartId() {
		return this.cartId;
	}

	public void setCartId(Integer cartId) {
		this.cartId = cartId;
	}

	public BigDecimal getProductPrice() {
		return this.productPrice;
	}

	public void setProductPrice(BigDecimal productPrice) {
		this.productPrice = productPrice;
	}

	public BigDecimal getShippingPrice() {
		return this.shippingPrice;
	}

	public void setShippingPrice(BigDecimal shippingPrice) {
		this.shippingPrice = shippingPrice;
	}

	public BigDecimal getTaxPrice() {
		return this.taxPrice;
	}

	public void setTaxPrice(BigDecimal taxPrice) {
		this.taxPrice = taxPrice;
	}

	public BigDecimal getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(BigDecimal totalPrice) {
		this.totalPrice = totalPrice;
	}

	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	public Set getCartitems() {
		return this.cartitems;
	}

	public void setCartitems(Set cartitems) {
		this.cartitems = cartitems;
	}

}
