package com.tech_freaks.shopcart.model;

// Generated Jun 19, 2015 4:48:46 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private Integer productId;
	private String name;
	private String partnumber;
	private String description;
	private String thumbnailUrl;
	private char buyable;
	private BigDecimal unitprice;

	public Product() {
	}

	public Product(String name, String partnumber, String description,
			char buyable, BigDecimal unitprice) {
		this.name = name;
		this.partnumber = partnumber;
		this.description = description;
		this.buyable = buyable;
		this.unitprice = unitprice;
	}

	public Product(String name, String partnumber, String description,
			String thumbnailUrl, char buyable, BigDecimal unitprice) {
		this.name = name;
		this.partnumber = partnumber;
		this.description = description;
		this.thumbnailUrl = thumbnailUrl;
		this.buyable = buyable;
		this.unitprice = unitprice;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPartnumber() {
		return this.partnumber;
	}

	public void setPartnumber(String partnumber) {
		this.partnumber = partnumber;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getThumbnailUrl() {
		return this.thumbnailUrl;
	}

	public void setThumbnailUrl(String thumbnailUrl) {
		this.thumbnailUrl = thumbnailUrl;
	}

	public char getBuyable() {
		return this.buyable;
	}

	public void setBuyable(char buyable) {
		this.buyable = buyable;
	}

	public BigDecimal getUnitprice() {
		return this.unitprice;
	}

	public void setUnitprice(BigDecimal unitprice) {
		this.unitprice = unitprice;
	}

	

}
